manifest:
  remotes:
    - name: zmkfirmware
      url-base: https://github.com/B4nn4n4
  projects:
    - name: zmk
      remote: zmkfirmware
      revision: blade
      import: app/west.yml
  self:
    path: config
